import { DashboardData } from '@types/dashboard';

export const mockDashboardData: DashboardData = {
  summary: [
    {
      id: 'low-stock',
      label: 'Low Stock Items',
      value: 12,
      format: 'number',
      change: 3,
      changeDirection: 'up',
      helperText: 'Items below minimum threshold',
    },
    {
      id: 'total-valuation',
      label: 'Total Inventory Valuation',
      value: 125350.75,
      format: 'currency',
      change: 8.2,
      changeDirection: 'up',
      helperText: 'Current total value',
    },
    {
      id: 'avg-turnover',
      label: 'Avg Turnover Rate',
      value: 68.5,
      format: 'percentage',
      change: 5.3,
      changeDirection: 'down',
      helperText: 'Based on past 30 days',
    },
    {
      id: 'stock-days',
      label: 'Avg Stock Days',
      value: 45,
      format: 'duration',
      change: 2.1,
      changeDirection: 'up',
      helperText: 'Days until restock needed',
    },
  ],
  turnover: [
    {
      id: 'daily-turnover',
      title: 'Daily Turnover Trend',
      period: 'daily',
      description: 'Last 7 days of inventory movement',
      type: 'line',
      series: [
        {
          id: 'units-moved',
          label: 'Units Moved',
          color: '#667eea',
          data: [
            { label: 'Mon', value: 245 },
            { label: 'Tue', value: 312 },
            { label: 'Wed', value: 289 },
            { label: 'Thu', value: 367 },
            { label: 'Fri', value: 421 },
            { label: 'Sat', value: 389 },
            { label: 'Sun', value: 198 },
          ],
        },
      ],
    },
    {
      id: 'weekly-valuation',
      title: 'Weekly Valuation Comparison',
      period: 'weekly',
      description: 'Valuation trends over the past 4 weeks',
      type: 'bar',
      series: [
        {
          id: 'valuation',
          label: 'Valuation ($)',
          color: '#4f46e5',
          data: [
            { label: 'Week 1', value: 118200 },
            { label: 'Week 2', value: 121500 },
            { label: 'Week 3', value: 119800 },
            { label: 'Week 4', value: 125350 },
          ],
        },
        {
          id: 'target',
          label: 'Target ($)',
          color: '#10b981',
          data: [
            { label: 'Week 1', value: 120000 },
            { label: 'Week 2', value: 120000 },
            { label: 'Week 3', value: 120000 },
            { label: 'Week 4', value: 120000 },
          ],
        },
      ],
    },
    {
      id: 'monthly-trends',
      title: 'Monthly Stock Movement',
      period: 'monthly',
      description: 'Inventory turnover across the last 6 months',
      type: 'line',
      series: [
        {
          id: 'turnover-rate',
          label: 'Turnover Rate (%)',
          color: '#f59e0b',
          data: [
            { label: 'Jul', value: 62 },
            { label: 'Aug', value: 65 },
            { label: 'Sep', value: 71 },
            { label: 'Oct', value: 68 },
            { label: 'Nov', value: 73 },
            { label: 'Dec', value: 69 },
          ],
        },
      ],
    },
  ],
  alerts: [
    {
      id: 'alert-1',
      severity: 'critical',
      title: 'Critical Stock Level',
      message: 'Premium Clippers (SKU: CLR-001) has only 3 units remaining. Restock immediately.',
      timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      ctaLabel: 'View Item',
      ctaHref: '/inventory/CLR-001',
    },
    {
      id: 'alert-2',
      severity: 'warning',
      title: 'High Turnover Detected',
      message: 'Hair Gel Premium is selling 40% faster than usual this week.',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      ctaLabel: 'Adjust Forecast',
      ctaHref: '/forecasting',
    },
    {
      id: 'alert-3',
      severity: 'info',
      title: 'Restock Scheduled',
      message: 'Shampoo bottles restock order will arrive tomorrow at 10:00 AM.',
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-4',
      severity: 'success',
      title: 'Valuation Target Met',
      message: 'Inventory valuation exceeded the monthly target by 4.5%.',
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-5',
      severity: 'warning',
      title: 'Slow-Moving Stock',
      message: 'Beard Oil Classic has not moved in 45 days. Consider promotions.',
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      ctaLabel: 'View Item',
      ctaHref: '/inventory/BO-CLASSIC',
    },
  ],
  lastUpdated: new Date().toISOString(),
};
